### ISSUE TITLE
JaxbAnnotationIntrospector creates wrong element names in JSON when using XmlElementWrapper

### ISSUE THREAD

**Issue by LucasMadar** [FasterXML/jackson-module-jaxb-annotations#13]
It looks like this might be caused by the fix for Issue #7.

Given the following code:

``` java
@XmlElementWrapper( name="listOfItems" )
@XmlElement( name = "item" )
private List<String>    _items;
```

Jackson 1.x would generate JSON in the form of:

``` json
{ "listOfItems": [ "a", "b" ] }
```

Jackson 2.x generates JSON in the form of:

``` json
{ "item": [ "a", "b" ] }
```

**Comment by firatkucuk** [comment]
This should be the default behavior without any additional configuration.
