### ISSUE TITLE
Problem with XmlAdapter downcasting

### ISSUE THREAD

**Issue by somiranroy** [FasterXML/jackson-module-jaxb-annotations#36]
I like Jackson and it is awesome but this issue is killing me! -  http://jira.codehaus.org/browse/JACKSON-723. This is blocking me from adopting Jackson as a JSON generator. Can you please help.

The only difference between my problem and the Jira item is that I am using JaxbAnnotationModule instead of JacksonAnnotationIntrospector.

**Comment by cowtowncoder** [comment]
I suspect this fix:

https://github.com/FasterXML/jackson-databind/issues/731

which will be in 2.5.3 (and 2.6.0) might help here.

**Comment by cowtowncoder** [comment]
I do not have a way to reproduce the problem at this point, so closing. May be reopened with reproducible unit test / code.
