### ISSUE TITLE
ObejectMapper accepts other elements than specified in @XmlElements

### ISSUE THREAD

**Issue by smolarek999** [FasterXML/jackson-module-jaxb-annotations#38]
Hi,

I am working on project where we are using _JSON_ <-> _XML_ conversion. We are using auto-generated _JAXB_ beans (generated by _MOXY_).

I found some inconsistency with `xsd:choice` in xsd. In this case _Moxy_ will generate mapping like this:

``` Java
@XmlElements({ @XmlElement(name = "Type1", type = Type1.class),
            @XmlElement(name = "Type2", type = Type2.class) },
                        @XmlElement(name = "TypeN", type = TypeN.class) })
List<Objects> type1OrType2OrTypeN;
```

For such mapping _Jackson_ is expecting _JSON _like this:

``` javascript
{
    "type1OrType2OrTypeN":  [       
             {   "Type1": {}      },
             {   "Type2": {}    }      
      ]
}
```

It expect array which contains wrapping objects, where each object has specified type in key.

My findings:
1) Jackon will accept also different values (no expected form XSD perspecive), such us: string `["txt","txt1"]` or Object `[{"Object":{}}]` -> could it be fixed and restricted to only specified by `@XmlElement` ones??
2. When I provide different JsonObject than Object, Type1 or Type2,  it fails with no meaningful error message: `Could not resolve type id 'Type3' into a subtype of [simple type, class java.lang.Object]`. -> Could it be changed to error which will say which types are allowed?
3. JsonSchema for this elements brings no information about elements types, it only says that it is type of array. I do not have idea how valid JsonSchema should look like it this case. Maybe _anyOf_ with allowed types?

I've checked how moxy handle this scenario, since it has also JSON <-> XML feature, and it  that is handled differently. There is sample of valid Json:

``` javascript
{
    "Type1":   [ {},  {} ],
        "Type2" : []
}
```

Instead of having intermediate array element to store Type1 or Type2, it uses separate arrays for each type. It makes JsonSchema simpler because it simply say that object can contain array of Type1 or/and array of Type2. So maybe it is the way how this `@XmlElements` can be handled also in Jackson?

I've attaching simple testing classes

``` Java
@XmlRootElement(name = "foo")
@XmlAccessorType(XmlAccessType.FIELD)
public class XmlWithChoice {

    @XmlElements({ @XmlElement(name = "Type1", type = Type1.class),
            @XmlElement(name = "Type2", type = Type2.class) })
    private List<Object> items;

    @Override
    public String toString() {
        return ToStringBuilder.reflectionToString(this,
                ToStringStyle.SHORT_PREFIX_STYLE);
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Type1 {

        @XmlAttribute(name = "Code", required = true)
        protected String code;

        public String getCode() {
            return code;
        }

        public void setCode(String value) {
            this.code = value;
        }

        @Override
        public String toString() {
            return ToStringBuilder.reflectionToString(this,
                    ToStringStyle.SHORT_PREFIX_STYLE);
        }

    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Type2 {

        @XmlAttribute(name = "Code", required = true)
        protected String code;

        public String getCode() {
            return code;
        }

        public void setCode(String value) {
            this.code = value;
        }

        @Override
        public String toString() {
            return ToStringBuilder.reflectionToString(this,
                    ToStringStyle.SHORT_PREFIX_STYLE);
        }

    }

}
```

``` Java
public class XmlWithChoiceTest {

    ObjectMapper om;

    @Before
    public void setUp() {

        om = new ObjectMapper();

        AnnotationIntrospector jaxbAnnotationIntrospector = new JaxbAnnotationIntrospector(
                om.getTypeFactory());
        AnnotationIntrospector jacksonAnnotationIntrospector = new JacksonAnnotationIntrospector();

        AnnotationIntrospector pair = AnnotationIntrospector.pair(
                jaxbAnnotationIntrospector, jacksonAnnotationIntrospector);
        om.setAnnotationIntrospector(pair);

    }

    @Test(expected = JsonMappingException.class)
    public void shouldNotAcceptObjectAndString() throws Exception {
        String src = "{\"items\":[{\"Type1\":{\"Code\":\"ABC\"}},{\"Type2\":{\"Code\":\"GHI\"}},\"ABC\",{\"Object\":{\"Code\":\"GHI\"}}]}";
        XmlWithChoice readValue = om.readValue(src, XmlWithChoice.class);
    }

    @Test
    public void itShouldFailWithSomeMeaningfullError() throws Exception {
        String src = "{\"items\":[{\"Type3\":{\"Code\":\"ABC\"}},{\"Type2\":{\"Code\":\"GHI\"}},\"ABC\",{\"Object\":{\"Code\":\"GHI\"}}]}";
        om.readValue(src, XmlWithChoice.class);
    }

    @Test
    public void generateJsonSchema() throws Exception {

        SchemaFactoryWrapper visitor = new SchemaFactoryWrapper();
        om.acceptJsonFormatVisitor(om.constructType(XmlWithChoice.class),
                visitor);
        JsonSchema finalSchema = visitor.finalSchema();
        String schema = om.writeValueAsString(finalSchema);
        fail("It says only that items is type 'array' without any details");

    }
}
```

Thanks,
Pawel

**Comment by cowtowncoder** [comment]
One more note on `String`, specifically: the reason that succeeds is two-fold:

1. `String` is an `Object` AND
2. `String` is one of small number of "natural" types (along with `Long`, `Boolean` and `Double`) that are always serialized without additional type id, even in polymorphic case

The (2) part is something that I think will not be easy to change, so unfortunately I think we are stuck with that -- it is not the same as what JAXB implementation does, but it is the way Jackson's deserialization works.

However, on plus side, this does NOT mean that all kinds of types are accepted. Just `String`s and numbers.

**Comment by cowtowncoder** [comment]
Porject moved; may be re-filed at

https://github.com/FasterXML/jackson-modules-base/issues

if issue still exists.
