### ISSUE TITLE
2.4.6 JAR not available in Maven central

### ISSUE THREAD

**Issue by ilgrosso** [FasterXML/jackson-module-jaxb-annotations#41]
MISSING: http://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.4.6/jackson-module-jaxb-annotations-2.4.6.jar

**Comment by cowtowncoder** [comment]
Sigh. Maven Central bug of some sort: I pushed that successfully, promoted, did everything via Nexus. And somehow it manages to miss the freaking jar itself.

Thank you for reporting this. I'll need to contact Sonatype, figure out how to get this fixed.

**Comment by cowtowncoder** [comment]
Also looks like Afterburner jar:

http://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-afterburner/2.4.6/

is similarly missing.

**Comment by cowtowncoder** [comment]
Working with Sonatype support on this: they should be able to resolve it. Depending on what is needed, may take a while, but I'd expect this to be fixed within 24 hours.
Apologies for inconvenience here.

Also: if you find modules other than JAXB annotations and Afterburner (2 cases known so far), please add to:

https://issues.sonatype.org/browse/OSSRH-15205

**Comment by cowtowncoder** [comment]
Ok, I managed to figure out how to re-create release with local `release.properties`, push a new version, and Nexus seems to accept it.

Thank you for reporting this.

**Comment by ilgrosso** [comment]
Thx for fixing!
