### ISSUE TITLE
Conflicting getter definitions Exception

### ISSUE THREAD

**Issue by haribachala** [FasterXML/jackson-module-jaxb-annotations#42]
Hi
when two properties  having  Different @XmlElementWrapper names and same @XmlElement  name then exception occurring.

Exception: Caused by: java.lang.IllegalArgumentException: Conflicting getter definitions for property "Address"
example:

``` java
List<Address>  officeAddresses;
List<Address>  residenceAddresses;

    @XmlElement(name="Address")
    public List<Address> getResidenceAddresses() {
        return residenceAddresses;
    }

    @XmlElementWrapper(name="ResidenceAddress")
    public void setResidenceAddress(List<Address> residenceAddress) {
    this.residenceAddress= residenceAddress;
    }

    @XmlElement(name="Address")
    public List<Address> getOfficeAddresses() {
        return officeAddresses;
    }

    @XmlElementWrapper(name="OfficeAddress")
    public void setOfficeAddress(List<Address> officeAddresses) {
        this.officeAddresses= officeAddresses;
    }
```

How to handle this kind of things ?

eg:

``` xml
<officeAddress>
     <address>
</officeAddress>

<residenceAddress>
   <address>
</residenceAddress>
```

Not able create JSON Response for Above cases  using Jackson. 

Jettison working fine for above kind of issues.

**Comment by cowtowncoder** [comment]
Correct, this causes conflict currently because wrapper handling/resolution occurs at a later point, after duplicate checking. It is a problem.

**Comment by haribachala** [comment]
Thanks,

is there any work around will suggest to come out of this problem. the above code working with 1.9 version of Jackson.

**Comment by cowtowncoder** [comment]
Unfortunately I am not aware of a work-around for this problem.

**Comment by haribachala** [comment]
The following Workaround  will work for conflict issue.

- Annotate Getter Method with @Jsonproperty("Name").
  
 @Jsonproperty("Address"
   @XmlElement(name="Address")
    public List<Address> getOfficeAddresses() {
        return officeAddresses;
    }

**Comment by godgav** [comment]
I've found a workaround for this issue
```
List<Address>  officeAddresses;
List<Address>  residenceAddresses;
    @XmlElementWrapper(name="ResidenceAddress")
    @XmlElements(@XmlElement(name="Address"))
    public List<Address> getResidenceAddresses() {
        return residenceAddresses;
    }

    @XmlElementWrapper(name="OfficeAddress")
    @XmlElements(@XmlElement(name="Address"))
    public List<Address> getOfficeAddresses() {
        return officeAddresses;
    }
```

**Comment by cowtowncoder** [comment]
@godgav Thank you for sharing your workaround.

**Comment by ag-cmcgregor** [comment]
@godgav +1 for the workaround :)

**Comment by cowtowncoder** [comment]
Project has moved, so although I think problem exists in some form, would need to be re-filed at:

https://github.com/FasterXML/jackson-modules-base/issues
