### ISSUE TITLE
Get it to work with wildfly 8.2.0

### ISSUE THREAD

**Issue by franciscocpg** [FasterXML/jackson-module-jaxb-annotations#45]
Someone managed to make this module work with wildfly 8.2.0?
@XmlTransient annotation not working.

**Comment by cowtowncoder** [comment]
You may want to send the question to user mailing list at `https://groups.google.com/forum/#!forum/jackson-user` -- not many users read github issues.
I do not the answer and do not recall this being discussed on mailing lists.
