### ISSUE TITLE
setNameUsedForXmlValue causes values to show up twice in the JSON output.

### ISSUE THREAD

**Issue by samielhini** [FasterXML/jackson-module-jaxb-annotations#46]
Example here I called setNameUsedForXmlValue("$") :

```json
{
  "RequestId" : {
    "IdentificationID" : {
      "value" : "1d9d7f5d-9ec3-4143-b2b3-ec6bea4ea9d7",
      "$" : "1d9d7f5d-9ec3-4143-b2b3-ec6bea4ea9d7"
    }
  },
  "CommandType" : "GET_PERSON",
  "Person" : {
    "PersonId" : {
      "IdentificationID" : {
        "value" : "473efc90-f254-453c-94ab-592aac3d363b",
        "$" : "473efc90-f254-453c-94ab-592aac3d363b"
      }
    },
    "PersonSSNIdentification" : null
  }
}
```

**Comment by cowtowncoder** [comment]
Could you also include POJO you use; afterwise it is difficult to reproduce the problem you are seeing.

Also: how do you manage to do this for JSON output? I thought this would only affect XML output, not JSON output.

**Comment by samielhini** [comment]
I added the JAxbIntrospector to the ObjectMapper.

Sami Elhini
Creatrix, Inc
443-745-5164
sami.elhini@creatrixinc.com

On Aug 3, 2015, at 14:03, Tatu Saloranta <notifications@github.com> wrote:

Could you also include POJO you use; afterwise it is difficult to reproduce
the problem you are seeing.

Also: how do you manage to do this for JSON output? I thought this would
only affect XML output, not JSON output.

—
Reply to this email directly or view it on GitHub
<https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/46#issuecomment-127353830>
.

**Comment by cowtowncoder** [comment]
Ok. But to reproduce this, I will need POJO definition as well.

**Comment by samielhini** [comment]
I will upload as soon as I can.

Sami Elhini
Creatrix, Inc
443-745-5164
sami.elhini@creatrixinc.com

On Aug 3, 2015, at 14:12, Tatu Saloranta <notifications@github.com> wrote:

Ok. But to reproduce this, I will need POJO definition as well.

—
Reply to this email directly or view it on GitHub
<https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/46#issuecomment-127356794>
.

**Comment by samielhini** [comment]
How do I send the code to you?

On Mon, Aug 3, 2015 at 2:15 PM, Sami Elhini <sami.elhini@creatrixinc.com>
wrote:

> I will upload as soon as I can.
>
> Sami Elhini
> Creatrix, Inc
> 443-745-5164
> sami.elhini@creatrixinc.com
>
> On Aug 3, 2015, at 14:12, Tatu Saloranta <notifications@github.com> wrote:
>
> Ok. But to reproduce this, I will need POJO definition as well.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/46#issuecomment-127356794>
> .
>
>


-- 
Sami Elhini
IEEE Certified Biometrics Professional
President
Creatrix, Inc
P: 844-200-CRTX (2789)
M: 443-745-5164
F. 844-900-CRTX (2789)
sami.elhini@creatrixinc.com
http://www.creatrixinc.com

**Comment by samielhini** [comment]
https://github.com/samielhini/BiometrixModel

**Comment by cowtowncoder** [comment]
Typically you add it as a comment to the github issue. There is no point in emailing any code to me directly; although github updates are sent via email as well, to participants.

**Comment by samielhini** [comment]
I just shared a github repo with you that has all my code.

On Mon, Aug 3, 2015 at 6:06 PM, Tatu Saloranta <notifications@github.com>
wrote:

> Typically you add it as a comment to the github issue. There is no point
> in emailing any code to me directly; although github updates are sent via
> email as well, to participants.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/FasterXML/jackson-module-jaxb-annotations/issues/46#issuecomment-127418561>
> .
>



-- 
Sami Elhini
IEEE Certified Biometrics Professional
President
Creatrix, Inc
P: 844-200-CRTX (2789)
M: 443-745-5164
F. 844-900-CRTX (2789)
sami.elhini@creatrixinc.com
http://www.creatrixinc.com

**Comment by samielhini** [comment]
I am closing this ticket.  The solution to my problem is this: 

JaxbAnnotationIntrospector introspector = new JaxbAnnotationIntrospector(TypeFactory.defaultInstance(), false);

Passing "true" for the second argument was the issue.
