### ISSUE TITLE
JaxbAnnotationIntrospector does not pick up 'required' property of @XmlAttribute

### ISSUE THREAD

**Issue by phantomjinx** [FasterXML/jackson-module-jaxb-annotations#47]
While converting jaxb annotated classes into a JsonSchema, I noticed that attributes with the @XmlAttribute(required = true) annotation are included in the latter schema but do not respect the required property. Debugging the [JaxbAnnotationIntrospector](https://github.com/FasterXML/jackson-module-jaxb-annotations/blob/master/src/main/java/com/fasterxml/jackson/module/jaxb/JaxbAnnotationIntrospector.java), I noticed that [hasRequiredMarker()](https://github.com/FasterXML/jackson-module-jaxb-annotations/blob/master/src/main/java/com/fasterxml/jackson/module/jaxb/JaxbAnnotationIntrospector.java#L1044) only looks for the @XmlElement annotation and not the @XmlAttribute annotation, despite the latter being checked by this method.

**Comment by cowtowncoder** [comment]
Good catch, thank you for reporting it. I'll have a look.
