### ISSUE TITLE
XmlIDREF not being honored, causes infinite recursion

### ISSUE THREAD

**Issue by rpatrick00** [FasterXML/jackson-module-jaxb-annotations#50]
I have a simple Company/Employee example where the Employee class looks like this:

```java
@XmlAccessorType(XmlAccessType.FIELD)
public class Employee {

  @XmlAttribute
  @XmlID
  private String id;

  @XmlAttribute
  private String name;

  @XmlIDREF
  private Employee manager;

  @XmlElement(name="report")
  @XmlIDREF
  private List<Employee> reports;

  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public Employee getManager() {
    return manager;
  }
  public void setManager(Employee manager) {
    this.manager = manager;
  }
  public List<Employee> getReports() {
    return reports;
  }
  public void setReports(List<Employee> reports) {
    this.reports = reports;
  }
  public Employee() {
    reports = new ArrayList<Employee>();
  }
} 
```

When using JAXB to write the data, I get what I expect:

<pre>
&lt;?xml version="1.0" encoding="UTF-8" standalone="yes"?&gt;
&lt;company&gt;
    &lt;employee id="1" name="Jane Doe"&gt;
        &lt;report&gt;2&lt;/report&gt;
        &lt;report&gt;3&lt;/report&gt;
    &lt;/employee&gt;
    &lt;employee id="2" name="John Smith"&gt;
        &lt;manager&gt;1&lt;/manager&gt;
    &lt;/employee&gt;
    &lt;employee id="3" name="Anne Jones"&gt;
        &lt;manager&gt;1&lt;/manager&gt;
    &lt;/employee&gt;
&lt;/company&gt;
</pre>

When using Jackson, I get an infinite loop that starts out like this:

<pre>
&lt;?xml version='1.1' encoding='UTF-8'?&gt;&lt;Company&gt;&lt;employees&gt;
    &lt;employees&gt;
      &lt;id&gt;1&lt;/id&gt;
      &lt;name&gt;Jane Doe&lt;/name&gt;
      &lt;reports&gt;
        &lt;reports&gt;
          &lt;id&gt;2&lt;/id&gt;
          &lt;name&gt;John Smith&lt;/name&gt;
          &lt;manager&gt;
            &lt;id&gt;1&lt;/id&gt;
            &lt;name&gt;Jane Doe&lt;/name&gt;
            &lt;reports&gt;
              &lt;reports&gt;
                &lt;id&gt;2&lt;/id&gt;
                &lt;name&gt;John Smith&lt;/name&gt;
                &lt;manager&gt;
                  &lt;id&gt;1&lt;/id&gt;
                  &lt;name&gt;Jane Doe&lt;/name&gt;
                  &lt;reports&gt;
                    &lt;reports&gt;
                      &lt;id&gt;2&lt;/id&gt;
                      &lt;name&gt;John Smith&lt;/name&gt;
                      &lt;manager&gt;
                        &lt;id&gt;1&lt;/id&gt;
                        &lt;name&gt;Jane Doe&lt;/name&gt;
                        &lt;reports&gt;
                          &lt;reports&gt;
                            &lt;id&gt;2&lt;/id&gt;
                            &lt;name&gt;John Smith&lt;/name&gt;
                            &lt;manager&gt;
                              &lt;id&gt;1&lt;/id&gt;
                              &lt;name&gt;Jane Doe&lt;/name&gt;
                              &lt;reports&gt;
                                &lt;reports&gt;
                                  &lt;id&gt;2&lt;/id&gt;
                                  &lt;name&gt;John Smith&lt;/name&gt;
                                  &lt;manager&gt;
                                    &lt;id&gt;1&lt;/id&gt;
                                    &lt;name&gt;Jane Doe&lt;/name&gt;
                                    &lt;reports&gt;
                                      &lt;reports&gt;
                                        &lt;id&gt;2&lt;/id&gt;
                                        &lt;name&gt;John Smith&lt;/name&gt;
                                        &lt;manager&gt;
...
</pre>
I am using Jackson 2.4.3

**Comment by cowtowncoder** [comment]
Challenge here is that JAXB annotations can only be used to the degree they can be translated to concepts Jackson supports. On plus side, Jackson databind does support Object Identity handling (usually via `@JsonIdentityInfo` annotation). On down side, equivalent of that annotation usually has to be on Object type being referenced (here, `Employee`). But... it is actually possibly to also specify it on property.

So maybe it might be possible to support this after all.

**Comment by cowtowncoder** [comment]
Actually, looking at `JaxbAnnotationIntrospector`, `@XmlIDREF` is sort of supported, ever since version 2.0. So I am not sure what is going on here. If possible, it would be nice to verify behavior with a more recent version, ideally 2.6.3.

**Comment by rpatrick00** [comment]
Same results with 2.6.3

**Comment by rpatrick00** [comment]
I figured out that I needed to create and set the JaxbAnnotationInspector explicitly to make it work.  Sorry for the noise.

**Comment by cowtowncoder** [comment]
@rpatrick00 No problem, thank you for update and closing the ticket.
