### ISSUE TITLE
The "Annotated" class in the dependency "jackson-databind" package has deprecated the getType() method Since 2.7

### ISSUE THREAD

**Issue by mxi1** [FasterXML/jackson-module-jaxb-annotations#55]
from the source code, jackson-module-jaxb-annotations depends on the "jackson-databind" package; for example, in https://github.com/FasterXML/jackson-module-jaxb-annotations/blob/master/src/main/java/com/fasterxml/jackson/module/jaxb/JaxbAnnotationIntrospector.java line 1606:
```Java
    protected JavaType _fullSerializationType(AnnotatedMember am) {
        return am.getType();
    }
```
However, when I cross-reference the __AnnotatedMember__ class and its super class __Annotated__, from the code file: https://github.com/FasterXML/jackson-databind/blob/2.7/src/main/java/com/fasterxml/jackson/databind/introspect/Annotated.java

Since line 65, the comment says:
```Java
    /**
     * @deprecated Since 2.7 Use {@link #getType()} instead. To be removed from 2.8.
     */
    @Deprecated
    public final JavaType getType(TypeBindings bogus) {
        return getType();
    }
```

Actually, I have met the relevant error when I am using the __spring-boot (1.3.2.RELEASE)__ framework, which makes me a little freak out, and the error message looks like:

>2016-02-25 08:28:04.093 ERROR 21983 --- [nio-8080-exec-3] o.a.c.c.C.[.[.[/].[servletContainer]     : Servlet.service() for servlet [servletContainer] in context with path [] threw exception [org.glassfish.jersey.server.ContainerException: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType()Lcom/fasterxml/jackson/databind/JavaType;] with root cause 
>
>java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.getType()Lcom/fasterxml/jackson/databind/JavaType;
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector._fullSerializationType(JaxbAnnotationIntrospector.java:1606) ~[jackson-module-jaxb-annotations-2.7.1.jar!/:2.7.1]
	at com.fasterxml.jackson.module.jaxb.JaxbAnnotationIntrospector._findContentAdapter(JaxbAnnotationIntrospector.java:1557) ~[jackson-module-jaxb-annotations-2.7.1.jar!/:2.7.1]
>

Can you evaluate if it is one bug, and could you provide one possible solution? 

Thank you very much!

**Comment by cowtowncoder** [comment]
I am not 100% sure what the intended bug here is. There was unfortunately an accidental breaking change in 2.7.0, fixed in 2.7.1, related to (now-)deprecated `TypeFactory` methods, but those are the only things I am awre of

**Comment by mxi1** [comment]
In 2.7.1 version of __jackson-databind__ package, the _getType()_ method has been removed from the __Annotated__ class, which doesn't help to solve the problem. 

Do you know if there is any alternative implementation to the `am.getType();` code? @cowtowncoder 

Thanks.

**Comment by cowtowncoder** [comment]
@mxi1 But 2.7 version of JAXB annotations module does not call such method; it calls `getType()` which takes no argument. Method has not been removed either; it has just been marked as deprecated, that is, not to be called by new code, and to be removed eventually (whether that be in 2.8 or not; probably it will not be removed quite that soon).

At this point I would need a unit test to show actual problem.
