### ISSUE TITLE
@XmlAttribute and @XmlAnyAttribute not supported correctly

### ISSUE THREAD

**Issue by puce77** [FasterXML/jackson-module-jaxb-annotations#59]
When serializing [javax.ws.rs.core.Link.JaxbLink](http://docs.oracle.com/javaee/7/api/javax/ws/rs/core/Link.JaxbLink.html) the output is wrong

The uri gets written as "uri" instead of "href" and the params map as a map instead of additional properties.

**Comment by cowtowncoder** [comment]
@puce77 Those would be JAX-RS (2.0) types, not included in JAXB, so I think the module for this one would be `jackson-jaxrs-proiders`. Behavior is probably due to default POJO introspection used which finds properties you mention. Related to that: why do you think representation should be different (f.ex. name of logical `uri` property as `href`)? Is there a specification of some kind that suggests what JSON serialization ought to be used?

Regardless I don't think values can be deserialized at this point, without using mix-in annotations or custom deserializer, so some work would be useful.

**Comment by puce77** [comment]
[JaxbLink](https://java.net/projects/jax-rs-spec/sources/api/content/jaxrs-api/src/main/java/javax/ws/rs/core/Link.java?rev=aa29f1fd3377096a871e30e9b644193785f525aa) is a JAXB class containing JAXB annotations.

It specifies:

       @XmlAttribute(name = "href")
        public URI getUri() {

and

        @XmlAnyAttribute
        public Map<QName, Object> getParams() {

**Comment by puce77** [comment]
In HATEOAS links are usually represented like this:
```
"links" : [
                {
                    "rel": "self",
                    "href": "http://example.com/people/1"
                }
            ]
```

**Comment by cowtowncoder** [comment]
Ok; so class is JAXB annotated? `@XmlAttribute` should be supported (assuming JAXB annotation introspector) is registered. `@XmlAnyAttribute` is not yet supported; perhaps it could act as an alias for `@JsonAnyGetter`.

It would be great to get a reproduction that just has class definition similar to `JaxbLink`. I should be able to create one if/as necessary.

**Comment by cowtowncoder** [comment]
Some more findings: `@XmlAnyAttribute` unfortunately can not be supported: it requires XML/JAXB specific dealing with `Map<QName,Object>`; for setters Jackson also requires use of 2-argument method (or in future possible field). All in all this is not and will not be supported.

As to `@XmlAttribute`, that should work and is supported. A test case would be needed to show how it fails; javadoc linked-to also does not list JAXB annotations (unless I missed it?). If annotation is in field, perhaps it would be question of visibility. Regardless, some form of problem reproduction is needed.

**Comment by cowtowncoder** [comment]
Project moved; if problem still persists (considering comments on inability support "any attribute"; need for test case for `@XmlAttribute`), may be re-filed at:

https://github.com/FasterXML/jackson-modules-base/issues
