### ISSUE TITLE
What is the license for this module? 

### ISSUE THREAD

**Issue by jeff-luszcz** [FasterXML/jackson-module-jaxb-annotations#62]
I can not find a license file in this package or in the source.
What license are these materials under?

thanks
  Jeff

**Comment by cowtowncoder** [comment]
Apache License 2.0. Information can be found from couple of places:

* From `src/main/resources` so it is packaged in source and binary jars
* From pom.xml, although indirectly in parent pom.
* Project wiki has (or should have -- I'll double-check) it mentioned
